---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-prom-svc
spec:
  selector:
    app: nginx-ingress-prom
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
...
